name: ssnbuilds
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_gutter: ^2.2.0
  flutter_web_plugins:
    sdk: flutter
  go_router: ^17.0.1
  responsive_framework: ^1.5.1

dev_dependencies:
  build_runner: ^2.10.5
  flutter_gen_runner: ^5.12.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: minecraft
      fonts:
        - asset: assets/fonts/minecraft/minecraft_regular.otf
        - asset: assets/fonts/minecraft/minecraft_bold.otf
          weight: 700
    - family: minecraft_block
      fonts:
        - asset: assets/fonts/minecraft/minecraft_block.ttf
          weight: 900

  assets:
    # - assets/bg/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/logo/
