name: server
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  database:
    path: ../database
  dotenv: ^4.2.0
  shared:
    path: ../shared

dev_dependencies:
  dart_frog_lint: ^0.1.0
  mocktail: ^1.0.3
  test: ^1.25.5
