name: shared
description: A starting point for Dart libraries or applications.
publish_to: none
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
 
  freezed: ^3.2.4
  freezed_annotation: ^3.1.0
# path: ^1.9.0
dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  build_runner: ^2.10.5
